### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by p0o** [MyCryptoHQ/xmr-core#23]
I just noticed that many good developments are happening on this repo which is getting much better than the original one that is following the cpp binding path.

Would you be interested to publish a prebuilt ES5 friendly NPM package of this repository?

**Comment by HenryNguyen5** [comment]
Hey @p0o! I'd love to publish this library, just havent gotten around to setting up Lerna to do so. If you'd like to contribute, feel free to tackle this on if you can get to it before I do!

**Comment by p0o** [comment]
Well, I expect you guys are willing to publish it with your NPM account, not mine!

**Comment by HenryNguyen5** [comment]
@p0o, you should be good to go now, happy coding!

**Comment by p0o** [comment]
@HenryNguyen5 Thanks but did you also publish it on NPM?
